### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by ironlion27** [ruippeixotog/docker-google-musicmanager#10]
Anyway to see upload progress/status.  Passed all environmental variables on run correctly.  Gave 2 factor authentication via VNC.  But VNC now a black screen and upon 'docker attach' there is no info.  No info in my appdata location either.  Please advise.

**Comment by ruippeixotog** [comment]
Hi! After a successful startup, a google-musicmanager.log file should be created in the appdata directory, together with some database files (*.db). Are you sure you mounted the volume correctly?

**Comment by ironlion27** [comment]
Volume was not mounted correctly...my sshfs mount had timed out by time I got the docker started.  Issue closed.
